backend: !filesystem
  directory: "/var/lib/lust/images"

base_serving_path: "/images"  # Serve buckets out of `/images`

global_cache:
  max_images: 1000    # At most cache 1000 images.
  # max_capacity: 500   # Or we can set 500MB max capacity.

buckets:
  bis-profile-pictures:  # PROFILE_BUCKET
    mode: jit
    formats:
      png: true
      jpeg: true
      webp: true
      gif: false
      webp_config:
        quality: 90
        method: 6
        threading: true
      original_image_store_format: jpeg
    default_serving_format: webp
    default_serving_preset: medium-square
    presets:
      medium-square:
        width: 500
        height: 500
    cache: null

  bis-event-images:  # EVENT_BUCKET
    mode: jit
    formats:
      png: true
      jpeg: true
      webp: true
      gif: false
      webp_config:
        quality: 90
        method: 6
        threading: true
      original_image_store_format: jpeg
    default_serving_format: webp
    default_serving_preset: medium-rectangle
    presets:
      medium-rectangle:
        width: 800
        height: 600
    cache: null

  profile-images:  # Keeping the original bucket for compatibility
    mode: jit
    formats:
      png: true
      jpeg: true
      webp: true
      gif: false
      webp_config:
        quality: 90
        method: 6
        threading: true
      original_image_store_format: jpeg
    default_serving_format: webp
    default_serving_preset: medium-square
    presets:
      medium-square:
        width: 500
        height: 500
    cache: null